import { JobStatus } from './status';

export const allowedTransitions: Record<JobStatus, JobStatus[]> = {
    DRAFT: ['INCOMING', 'CANCELLED'],
    INCOMING: ['NEEDS_ASSIGNMENT', 'ASSIGNMENT_PENDING', 'OPENED', 'PENDING_ASSIGNMENT', 'QUOTE_PENDING', 'ADMIN_HOLD', 'CANCELLED'],
    NEEDS_ASSIGNMENT: ['ASSIGNMENT_PENDING', 'OPENED', 'PENDING_ASSIGNMENT', 'QUOTE_PENDING', 'ADMIN_HOLD', 'CANCELLED'],
    ASSIGNMENT_PENDING: ['BOOKED', 'NEEDS_ASSIGNMENT', 'ADMIN_HOLD', 'CANCELLED'],
    OPENED: ['BOOKED', 'NEEDS_ASSIGNMENT', 'INCOMING', 'ADMIN_HOLD', 'CANCELLED'],
    PENDING_ASSIGNMENT: ['ASSIGNMENT_PENDING', 'OPENED', 'QUOTE_PENDING', 'BOOKED', 'NEEDS_ASSIGNMENT', 'INCOMING', 'CANCELLED'],
    QUOTE_PENDING: ['NEEDS_ASSIGNMENT', 'ASSIGNMENT_PENDING', 'BOOKED', 'ADMIN_HOLD', 'CANCELLED'],
    BOOKED: ['SESSION_COMPLETED', 'TIMESHEET_SUBMITTED', 'ADMIN_HOLD', 'CANCELLED'],
    SESSION_COMPLETED: ['TIMESHEET_SUBMITTED', 'ADMIN_HOLD'],
    TIMESHEET_SUBMITTED: ['TIMESHEET_VERIFIED', 'VERIFIED', 'ADMIN_HOLD'],
    TIMESHEET_VERIFIED: ['READY_FOR_INVOICE', 'INVOICING'],
    VERIFIED: ['READY_FOR_INVOICE', 'INVOICING'],
    READY_FOR_INVOICE: ['INVOICED'],
    INVOICING: ['INVOICED', 'READY_FOR_INVOICE'],
    INVOICED: ['PAID'],
    PAID: [],
    ADMIN_HOLD: ['NEEDS_ASSIGNMENT', 'ASSIGNMENT_PENDING', 'BOOKED', 'SESSION_COMPLETED', 'TIMESHEET_SUBMITTED', 'READY_FOR_INVOICE', 'CANCELLED'],
    CANCELLED: [],
};

export const canTransition = (current: JobStatus, next: JobStatus): boolean => {
    return allowedTransitions[current]?.includes(next) ?? false;
};
